# Generated by Django 5.0.1 on 2024-12-17 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0003_alter_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='apirest.category'),
        ),
    ]
