# Generated by Django 5.0.1 on 2024-12-17 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0004_alter_merchant_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='merchant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='apirest.merchant'),
        ),
    ]
